"""create vaccine table

Revision ID: d862ea21bf97
Revises: be3ad84d286c
Create Date: 2026-03-07 04:54:12.723402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd862ea21bf97'
down_revision = 'be3ad84d286c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_applied', sa.DateTime(), nullable=False),
    sa.Column('next_dose', sa.DateTime(), nullable=True),
    sa.Column('vet', sa.String(length=100), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccines')
    # ### end Alembic commands ###
